version: '3'

services:

  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: fullcycle-nest-back
    ports: 
      - 3000:3000
    volumes: 
      - .:/home/node/app
    depends_on: 
      - db
    extra_hosts: 
      - "host.docker.internal:172.17.0.1"

  db:
    build: .docker/postgres
    container_name: fullcycle-nest-back-db
    restart: always
    tty: true
    volumes: 
      - .docker/dbdata:/var/lib/postgressql/data
    environment: 
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=nest
