apiVersion: apps/v1
kind: Deployment
metadata:
  name: bank-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bank-api
  template:
    metadata:
      labels:
        app: bank-api
    spec:
      containers:
        - name: bank-api
          image: caiquebb/bank-api-nest
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: bank-api-secret
          
          volumeMounts:
            - name: bank-api-volume
              mountPath: /home/node/app/.env
              subPath: .env

      volumes:
        - name: bank-api-volume
          configMap:
            name: bank-api-conf
            items:
              - key: env
                path: .env
